# These secrets are for dev purposes only. Not to be used in production
mysql:
  mysqlUser: kolide
  mysqlPassword: mysqlPassword
  mysqlDatabase: kolide
redis:
  redisPassword: redisPassword
fleet:
  auth:
    jwt_key: jwt_key
elasticsearch:
  username: elasticsearch
  password: MY_VERY_SECURE_ELASTIC_PASSWORD
