# These secrets are for dev purposes only. DO NOT use in production
mysql:
  mysqlUser: kolide
  mysqlPassword: mysqlPassword
  mysqlDatabase: kolide
redis:
  redisPassword: redisPassword
fleet:
  auth:
    jwt_key: jwt_key
elasticsearch:
  username: elastic
  password: MY_VERY_SECURE_ELASTIC_PASSWORD
kibana:
  username: kibana
  password: MY_VERY_SECURE_KIBANA_PASSWORD
